# Generated by Django 5.2.10 on 2026-02-02 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_groups"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "google_id",
                    models.CharField(
                        help_text="Google's unique user identifier (sub claim)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "google_email",
                    models.EmailField(
                        help_text="Email from Google account (may differ from user email)",
                        max_length=254,
                    ),
                ),
                (
                    "google_picture",
                    models.URLField(
                        blank=True, help_text="Profile picture URL from Google"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Google Account",
                "verbose_name_plural": "Google Accounts",
            },
        ),
    ]
