# Generated by Django 5.2.10 on 2026-02-03 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_core_documents",
                to="employees.employee",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="core_docume_content_343c2e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["tenant", "content_type"], name="core_docume_tenant__3ca250_idx"
            ),
        ),
    ]
