# Generated by Django 5.2.10 on 2026-01-30 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('timetracking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='timeentrytype',
            name='unique_time_entry_type_code_per_tenant',
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='timeentrytype',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='timeentrytype',
            unique_together={('tenant', 'code')},
        ),
    ]
