# Generated by Django 5.2.10 on 2026-01-30 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='department',
            name='unique_department_code_per_tenant',
        ),
        migrations.RemoveConstraint(
            model_name='employee',
            name='unique_employee_id_per_tenant',
        ),
        migrations.AlterField(
            model_name='department',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='position',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('tenant', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('tenant', 'employee_id')},
        ),
    ]
