# Generated by Django 5.2.10 on 2026-01-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_department_unique_department_code_per_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='country',
            field=models.CharField(blank=True, help_text='ISO 3166-1 alpha-2 country code (e.g., US, GB, DE)', max_length=2),
        ),
        migrations.AddField(
            model_name='employee',
            name='timezone',
            field=models.CharField(blank=True, help_text='IANA timezone (e.g., America/New_York, Europe/London)', max_length=50),
        ),
    ]
