# Generated by Django 6.0.1 on 2026-01-31 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_add_location_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='country',
        ),
        migrations.AddField(
            model_name='department',
            name='country',
            field=models.CharField(blank=True, help_text='ISO 3166-1 alpha-2 country code (e.g., US, GB, DE)', max_length=2),
        ),
    ]
