# Generated by Django 6.0.1 on 2026-01-31 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='logo_icon',
            field=models.ImageField(blank=True, help_text='Compact icon/logo displayed when sidebar is collapsed', null=True, upload_to='tenant_logos/icons/'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='logo',
            field=models.ImageField(blank=True, help_text='Full logo displayed when sidebar is expanded', null=True, upload_to='tenant_logos/'),
        ),
    ]
