# Generated by Django 5.2.10 on 2026-01-30 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_department_unique_department_code_per_tenant_and_more'),
        ('tenants', '0001_initial'),
        ('timesheets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='timesheet',
            name='unique_timesheet_per_employee_period',
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='timesheetcomment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='timesheet',
            unique_together={('tenant', 'employee', 'period_start')},
        ),
    ]
