# Generated by Django 5.2.10 on 2026-01-30 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_department_unique_department_code_per_tenant_and_more'),
        ('leave', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='leavebalance',
            name='unique_leave_balance_per_employee_type_year',
        ),
        migrations.RemoveConstraint(
            model_name='leavetype',
            name='unique_leave_type_code_per_tenant',
        ),
        migrations.AlterField(
            model_name='holiday',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='leavebalance',
            unique_together={('tenant', 'employee', 'leave_type', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='leavetype',
            unique_together={('tenant', 'code')},
        ),
    ]
