# Generated by Django 5.2.10 on 2026-01-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_remove_leavebalance_unique_leave_balance_per_employee_type_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='country',
            field=models.CharField(blank=True, help_text='ISO 3166-1 alpha-2 country code for national holidays', max_length=2),
        ),
    ]
