# Generated by Django 6.0.1 on 2026-01-31 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_move_country_to_department'),
        ('leave', '0003_add_location_fields'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='external_id',
            field=models.CharField(blank=True, help_text='External identifier from API source', max_length=100),
        ),
        migrations.AddField(
            model_name='holiday',
            name='holiday_types',
            field=models.JSONField(blank=True, default=list, help_text='Types of holiday (e.g., Public, Bank, National)'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='local_name',
            field=models.CharField(blank=True, help_text='Holiday name in local language', max_length=255),
        ),
        migrations.AddField(
            model_name='holiday',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('nager_date', 'Nager.Date API')], default='manual', help_text='Origin of this holiday entry', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='holiday',
            constraint=models.UniqueConstraint(fields=('tenant', 'country', 'date', 'name'), name='unique_holiday_per_tenant_country_date'),
        ),
    ]
