# Generated by Django 5.2.10 on 2026-02-03 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contracts", "0001_initial"),
        ("employees", "0001_initial"),
        ("tenants", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contracts",
                to="employees.employee",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="contractdocument",
            name="contract",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="contracts.contract",
            ),
        ),
        migrations.AddField(
            model_name="contractdocument",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="contractdocument",
            name="uploaded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_documents",
                to="employees.employee",
            ),
        ),
        migrations.AddField(
            model_name="contracttype",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="contract_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contracts",
                to="contracts.contracttype",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contracttype",
            unique_together={("tenant", "code")},
        ),
    ]
